server:
  port: 8090
  context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EVENT_REGISTRATION
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  jackson:
    default-property-inclusion: non_empty
    serialization:
      fail-on-empty-beans: false
      indent-output: true
      write-dates-as-timestamps: false

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: eventregservice@gmail.com
    password: Somep@ssword
    properties.mail.smtp:
      auth: true
      starttls.enable: true

---

spring:
  profiles: integration

  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
         defauls-schema: public
         dialect:

  jackson:
      deserialization:
        accept-single-value-as-array: true

---

spring:
  profiles: db-setup

  jpa:
      hibernate:
        ddl-auto: create
      show-sql: true