server:
  port: 8090
  context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registrationdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  jackson:
    serialization:
      fail-on-empty-beans: false
      indent-output: true